[build]
rustflags = ["-Ctarget-feature=+aes,+sse2,+ssse3"]
rustdocflags = ["-Ctarget-feature=+aes,+sse2,+ssse3"]

[test]
rustflags = ["-Ctarget-feature=+aes,+sse2,+ssse3"]
rustdocflags = ["-Ctarget-feature=+aes,+sse2,+ssse3"]
