packages:
  - clients/js
  - clients/js/type-only-test
  - contracts/
  - examples/hardhat
  - examples/hardhat-boilerplate
  - examples/hardhat-boilerplate/frontend
  - examples/onchain-signer
  - examples/truffle
  - integrations/hardhat
