[package]
name = "sapphire-paratime"
version = "0.2.1-testnet"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2021"
license = "Apache-2.0"

[package.metadata.orc.release]
runtime-id = "0000000000000000000000000000000000000000000000000000000000000000"

[package.metadata.orc.test]
runtime-id = "000000000000000000000000000000000000000000000000a6d1e3ebf60dff6c"

[package.metadata.fortanix-sgx]
heap-size = 134217728
stack-size = 2097152
threads = 6
debug = false

[dependencies]
keymanager = { git = "https://github.com/oasisprotocol/keymanager-paratime", tag = "v0.3.2-testnet" }
module-evm = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "04944cbb7a3cf346acb2693b0a7dfda4ab0f9f63", package = "oasis-runtime-sdk-evm" }
oasis-runtime-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "04944cbb7a3cf346acb2693b0a7dfda4ab0f9f63" }

# Third party.
once_cell = "1.8.0"

[profile.release]
codegen-units = 1
lto = "thin"
